name: order_tracking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State Management
  flutter_bloc: ^8.1.1

  #Firebase
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_database: ^10.0.6

  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #UI
  cached_network_image: ^3.2.3
  flutter_svg_provider: ^1.0.3
  font_awesome_flutter: ^10.3.0

  #UTIL
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.3.0
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/patterns/
